In [3]:
import pandas as pd

In [7]:
info = {
    "Name":["Rahul","Omakr","Sagar"],
    "CGPA":[9.6,7.8,8.5]
}

df = pd.DataFrame(info)
print(df)

    Name  CGPA
0  Rahul   9.6
1  Omakr   7.8
2  Sagar   8.5

In [8]:
df

    Name  CGPA
0  Rahul   9.6
1  Omakr   7.8
2  Sagar   8.5

In [10]:
s = pd.Series([1,2,3,4,5])
print(s)

#index
print(s[0])
print(s[4])

0    1
1    2
2    3
3    4
4    5
dtype: int64
1
5

In [14]:
s = pd.Series([24,25,98,48,65],index = ["Rahul","Geeta","Nikita","Sambhav","Kashi"])

print(s)
print(s["Rahul"])
print(s["Kashi"])
print(s.index)

Rahul      24
Geeta      25
Nikita     98
Sambhav    48
Kashi      65
dtype: int64
24
65
Index(['Rahul', 'Geeta', 'Nikita', 'Sambhav', 'Kashi'], dtype='object')

In [5]:
# Series are homogensous
s = pd.Series([1,2,3,4,"hello"])
print(s)

0        1
1        2
2        3
3        4
4    hello
dtype: object

In [10]:
# vertrizero operation
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([1,2,3,4])
print(s1 + s2)

s1[0] = 100
chenged_s1 = s1.drop(0)
print(s1)
print(chenged_s1)

0    2
1    4
2    6
3    8
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [15]:
# DataFrame
info = {
    "Name" : ["Rhaul","Nikhil","Akash"],
    "Age" : [23,24,25],
    "GPA" : [9.8,8.6,7.4]
}

df = pd.DataFrame(info)
print(df,type(df))

print(df.index)
print(df.columns)

     Name  Age  GPA
0   Rhaul   23  9.8
1  Nikhil   24  8.6
2   Akash   25  7.4 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [12]:
df

     Name  Age  GPA
0   Rhaul   23  9.8
1  Nikhil   24  8.6
2   Akash   25  7.4

In [17]:
df = pd.DataFrame([["Rahul",24],["Rhoit",25],["Sumite",12]] , columns = ["Name","Age"])
print(df)

     Name  Age
0   Rahul   24
1   Rhoit   25
2  Sumite   12

In [20]:
import numpy as np 

np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr , columns = ["A","B","C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6